//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samayas.Tools.CodeAnalyzers.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Samayas.Tools.CodeAnalyzers.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforces that classes derived from EntityBase have a name ending with &apos;Entity&apos;..
        /// </summary>
        internal static string DataClassSuffixEntityForBaseEntityBaseClassAnalyzerDescription {
            get {
                return ResourceManager.GetString("DataClassSuffixEntityForBaseEntityBaseClassAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &apos;{0}&apos; inherits from EntityBase and must end with &apos;Entity&apos;.
        /// </summary>
        internal static string DataClassSuffixEntityForBaseEntityBaseClassAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("DataClassSuffixEntityForBaseEntityBaseClassAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherited EntityBase class name must end with &apos;Entity&apos;.
        /// </summary>
        internal static string DataClassSuffixEntityForBaseEntityBaseClassAnalyzerTitle {
            get {
                return ResourceManager.GetString("DataClassSuffixEntityForBaseEntityBaseClassAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforces that classes derived from EntityBase have a parameterless constructor..
        /// </summary>
        internal static string DataMethodEmptyConstructorForBaseEntityBaseClassAnalyzerDescription {
            get {
                return ResourceManager.GetString("DataMethodEmptyConstructorForBaseEntityBaseClassAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &apos;{0}&apos; inherits from EntityBase and must have a parameterless constructor for serialization..
        /// </summary>
        internal static string DataMethodEmptyConstructorForBaseEntityBaseClassAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("DataMethodEmptyConstructorForBaseEntityBaseClassAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherited EntityBase class must have a parameterless constructor.
        /// </summary>
        internal static string DataMethodEmptyConstructorForBaseEntityBaseClassAnalyzerTitle {
            get {
                return ResourceManager.GetString("DataMethodEmptyConstructorForBaseEntityBaseClassAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforces that test base-derived classes are annotated with [ExcludeFromCodeCoverage()]..
        /// </summary>
        internal static string TestClassAttributeExcludeFromCodeCoverageForBaseTestClassAnalyzerDescription {
            get {
                return ResourceManager.GetString("TestClassAttributeExcludeFromCodeCoverageForBaseTestClassAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &apos;{0}&apos; inherits from BaseTestClass and must be decorated with [ExcludeFromCodeCoverage()].
        /// </summary>
        internal static string TestClassAttributeExcludeFromCodeCoverageForBaseTestClassAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("TestClassAttributeExcludeFromCodeCoverageForBaseTestClassAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes inheriting from BaseTestClass must have [ExcludeFromCodeCoverage()].
        /// </summary>
        internal static string TestClassAttributeExcludeFromCodeCoverageForBaseTestClassAnalyzerTitle {
            get {
                return ResourceManager.GetString("TestClassAttributeExcludeFromCodeCoverageForBaseTestClassAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforces that classes derived from BaseViewModel have a name ending with &apos;ViewModel&apos;..
        /// </summary>
        internal static string WebClassSuffixForBaseViewModelClassAnalyzerDescription {
            get {
                return ResourceManager.GetString("WebClassSuffixForBaseViewModelClassAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &apos;{0}&apos; inherits from BaseViewModel and must end with &apos;ViewModel&apos;.
        /// </summary>
        internal static string WebClassSuffixForBaseViewModelClassAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("WebClassSuffixForBaseViewModelClassAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherited BaseViewModel class name must end with &apos;ViewModel&apos;.
        /// </summary>
        internal static string WebClassSuffixForBaseViewModelClassAnalyzerTitle {
            get {
                return ResourceManager.GetString("WebClassSuffixForBaseViewModelClassAnalyzerTitle", resourceCulture);
            }
        }
    }
}
