<Project Sdk="Aspire.AppHost.Sdk/13.1.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>0a06c39e-5ec3-4dba-bf68-6d62cf1db952</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UploadAndScan2Full\UploadAndScan2Full.csproj" />
  </ItemGroup>

</Project>
