//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samayas.CodeGenerator.Repositories {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class RepositoryGenerator : RepositoryGeneratorBase {
        
        
        private string _NamespaceNameField;
        
        public string NamespaceName {
            get {
                return this._NamespaceNameField;
            }
        }
        
        private string _EntityNameField;
        
        public string EntityName {
            get {
                return this._EntityNameField;
            }
        }
        
        private string _PrimaryKeyTypeField;
        
        public string PrimaryKeyType {
            get {
                return this._PrimaryKeyTypeField;
            }
        }
        
        private bool _IncludeAsyncField;
        
        public bool IncludeAsync {
            get {
                return this._IncludeAsyncField;
            }
        }
        
        private bool _IncludeLoggingField;
        
        public bool IncludeLogging {
            get {
                return this._IncludeLoggingField;
            }
        }
        
        private string _ModelUsingField;
        
        public string ModelUsing {
            get {
                return this._ModelUsingField;
            }
        }

        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 12 "RepositoryGenerator.tt"
            this.Write("\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing System.Linq;\r\n");
            
            #line default
            #line hidden
            
            #line 16 "RepositoryGenerator.tt"
 if (IncludeAsync) { 
            
            #line default
            #line hidden
            
            #line 17 "RepositoryGenerator.tt"
            this.Write("using System.Threading.Tasks;\r\n");
            
            #line default
            #line hidden
            
            #line 18 "RepositoryGenerator.tt"
 } 
            
            #line default
            #line hidden
            
            #line 19 "RepositoryGenerator.tt"
 if (IncludeLogging) { 
            
            #line default
            #line hidden
            
            #line 20 "RepositoryGenerator.tt"
            this.Write("using Microsoft.Extensions.Logging;\r\n");
            
            #line default
            #line hidden
            
            #line 21 "RepositoryGenerator.tt"
 } 
            
            #line default
            #line hidden
            
            #line 22 "RepositoryGenerator.tt"
            this.Write("using ");
            
            #line default
            #line hidden
            
            #line 22 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ModelUsing ));
            
            #line default
            #line hidden
            
            #line 22 "RepositoryGenerator.tt"
            this.Write(";\r\n\r\nnamespace ");
            
            #line default
            #line hidden
            
            #line 24 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( NamespaceName ));
            
            #line default
            #line hidden
            
            #line 24 "RepositoryGenerator.tt"
            this.Write("\r\n{\r\n    /// <summary>\r\n    /// Repository for ");
            
            #line default
            #line hidden
            
            #line 27 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 27 "RepositoryGenerator.tt"
            this.Write(" entities\r\n    /// Auto-generated on ");
            
            #line default
            #line hidden
            
            #line 28 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss") ));
            
            #line default
            #line hidden
            
            #line 28 "RepositoryGenerator.tt"
            this.Write("\r\n    /// Version used ");
            
            #line default
            #line hidden
            
            #line 29 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( this.GetType().AssemblyQualifiedName ));
            
            #line default
            #line hidden
            
            #line 29 "RepositoryGenerator.tt"
            this.Write("\r\n    /// </summary>\r\n    public class ");
            
            #line default
            #line hidden
            
            #line 31 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 31 "RepositoryGenerator.tt"
            this.Write("Repository : I");
            
            #line default
            #line hidden
            
            #line 31 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 31 "RepositoryGenerator.tt"
            this.Write("Repository\r\n    {\r\n        private readonly List<");
            
            #line default
            #line hidden
            
            #line 33 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 33 "RepositoryGenerator.tt"
            this.Write("> _dataStore;\r\n");
            
            #line default
            #line hidden
            
            #line 34 "RepositoryGenerator.tt"
 if (IncludeLogging) { 
            
            #line default
            #line hidden
            
            #line 35 "RepositoryGenerator.tt"
            this.Write("        private readonly ILogger<");
            
            #line default
            #line hidden
            
            #line 35 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 35 "RepositoryGenerator.tt"
            this.Write("Repository> _logger;\r\n\r\n        public ");
            
            #line default
            #line hidden
            
            #line 37 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 37 "RepositoryGenerator.tt"
            this.Write("Repository(ILogger<");
            
            #line default
            #line hidden
            
            #line 37 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 37 "RepositoryGenerator.tt"
            this.Write("Repository> logger)\r\n        {\r\n            _dataStore = new List<");
            
            #line default
            #line hidden
            
            #line 39 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 39 "RepositoryGenerator.tt"
            this.Write(">();\r\n            _logger = logger;\r\n        }\r\n");
            
            #line default
            #line hidden
            
            #line 42 "RepositoryGenerator.tt"
 } else { 
            
            #line default
            #line hidden
            
            #line 43 "RepositoryGenerator.tt"
            this.Write("\r\n        public ");
            
            #line default
            #line hidden
            
            #line 44 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 44 "RepositoryGenerator.tt"
            this.Write("Repository()\r\n        {\r\n            _dataStore = new List<");
            
            #line default
            #line hidden
            
            #line 46 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 46 "RepositoryGenerator.tt"
            this.Write(">();\r\n        }\r\n");
            
            #line default
            #line hidden
            
            #line 48 "RepositoryGenerator.tt"
 } 
            
            #line default
            #line hidden
            
            #line 49 "RepositoryGenerator.tt"
            this.Write("\r\n");
            
            #line default
            #line hidden
            
            #line 50 "RepositoryGenerator.tt"
 if (IncludeAsync) { 
            
            #line default
            #line hidden
            
            #line 51 "RepositoryGenerator.tt"
            this.Write("        public async Task<");
            
            #line default
            #line hidden
            
            #line 51 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 51 "RepositoryGenerator.tt"
            this.Write("> GetByIdAsync(");
            
            #line default
            #line hidden
            
            #line 51 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( PrimaryKeyType ));
            
            #line default
            #line hidden
            
            #line 51 "RepositoryGenerator.tt"
            this.Write(" id)\r\n        {\r\n");
            
            #line default
            #line hidden
            
            #line 53 "RepositoryGenerator.tt"
 if (IncludeLogging) { 
            
            #line default
            #line hidden
            
            #line 54 "RepositoryGenerator.tt"
            this.Write("            _logger.LogInformation(\"Retrieving {EntityName} with ID: {Id}\", nameo" +
                    "f(");
            
            #line default
            #line hidden
            
            #line 54 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 54 "RepositoryGenerator.tt"
            this.Write("), id);\r\n");
            
            #line default
            #line hidden
            
            #line 55 "RepositoryGenerator.tt"
 } 
            
            #line default
            #line hidden
            
            #line 56 "RepositoryGenerator.tt"
            this.Write("            return await Task.FromResult(_dataStore.FirstOrDefault(x => x.Id.Equa" +
                    "ls(id)));\r\n        }\r\n\r\n        public async Task<IEnumerable<");
            
            #line default
            #line hidden
            
            #line 59 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 59 "RepositoryGenerator.tt"
            this.Write(">> GetAllAsync()\r\n        {\r\n");
            
            #line default
            #line hidden
            
            #line 61 "RepositoryGenerator.tt"
 if (IncludeLogging) { 
            
            #line default
            #line hidden
            
            #line 62 "RepositoryGenerator.tt"
            this.Write("            _logger.LogInformation(\"Retrieving all {EntityName} entities\", nameof" +
                    "(");
            
            #line default
            #line hidden
            
            #line 62 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 62 "RepositoryGenerator.tt"
            this.Write("));\r\n");
            
            #line default
            #line hidden
            
            #line 63 "RepositoryGenerator.tt"
 } 
            
            #line default
            #line hidden
            
            #line 64 "RepositoryGenerator.tt"
            this.Write("            return await Task.FromResult(_dataStore.AsEnumerable());\r\n        }\r\n" +
                    "\r\n        public async Task AddAsync(");
            
            #line default
            #line hidden
            
            #line 67 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 67 "RepositoryGenerator.tt"
            this.Write(" entity)\r\n        {\r\n");
            
            #line default
            #line hidden
            
            #line 69 "RepositoryGenerator.tt"
 if (IncludeLogging) { 
            
            #line default
            #line hidden
            
            #line 70 "RepositoryGenerator.tt"
            this.Write("            _logger.LogInformation(\"Adding new {EntityName} entity\", nameof(");
            
            #line default
            #line hidden
            
            #line 70 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 70 "RepositoryGenerator.tt"
            this.Write("));\r\n");
            
            #line default
            #line hidden
            
            #line 71 "RepositoryGenerator.tt"
 } 
            
            #line default
            #line hidden
            
            #line 72 "RepositoryGenerator.tt"
            this.Write("            _dataStore.Add(entity);\r\n            await Task.CompletedTask;\r\n     " +
                    "   }\r\n\r\n        public async Task UpdateAsync(");
            
            #line default
            #line hidden
            
            #line 76 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 76 "RepositoryGenerator.tt"
            this.Write(" entity)\r\n        {\r\n");
            
            #line default
            #line hidden
            
            #line 78 "RepositoryGenerator.tt"
 if (IncludeLogging) { 
            
            #line default
            #line hidden
            
            #line 79 "RepositoryGenerator.tt"
            this.Write("            _logger.LogInformation(\"Updating {EntityName} with ID: {Id}\", nameof(" +
                    "");
            
            #line default
            #line hidden
            
            #line 79 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 79 "RepositoryGenerator.tt"
            this.Write("), entity.Id);\r\n");
            
            #line default
            #line hidden
            
            #line 80 "RepositoryGenerator.tt"
 } 
            
            #line default
            #line hidden
            
            #line 81 "RepositoryGenerator.tt"
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 81 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 81 "RepositoryGenerator.tt"
            this.Write(@" existing = _dataStore.FirstOrDefault(x => x.Id.Equals(entity.Id));
            if (existing != null)
            {
                int index = _dataStore.IndexOf(existing);
                _dataStore[index] = entity;
            }
            await Task.CompletedTask;
        }

        public async Task DeleteAsync(");
            
            #line default
            #line hidden
            
            #line 90 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( PrimaryKeyType ));
            
            #line default
            #line hidden
            
            #line 90 "RepositoryGenerator.tt"
            this.Write(" id)\r\n        {\r\n");
            
            #line default
            #line hidden
            
            #line 92 "RepositoryGenerator.tt"
 if (IncludeLogging) { 
            
            #line default
            #line hidden
            
            #line 93 "RepositoryGenerator.tt"
            this.Write("            _logger.LogInformation(\"Deleting {EntityName} with ID: {Id}\", nameof(" +
                    "");
            
            #line default
            #line hidden
            
            #line 93 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 93 "RepositoryGenerator.tt"
            this.Write("), id);\r\n");
            
            #line default
            #line hidden
            
            #line 94 "RepositoryGenerator.tt"
 } 
            
            #line default
            #line hidden
            
            #line 95 "RepositoryGenerator.tt"
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 95 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 95 "RepositoryGenerator.tt"
            this.Write(" entity = _dataStore.FirstOrDefault(x => x.Id.Equals(id));\r\n            if (entit" +
                    "y != null)\r\n            {\r\n                _dataStore.Remove(entity);\r\n         " +
                    "   }\r\n            await Task.CompletedTask;\r\n        }\r\n");
            
            #line default
            #line hidden
            
            #line 102 "RepositoryGenerator.tt"
 } else { 
            
            #line default
            #line hidden
            
            #line 103 "RepositoryGenerator.tt"
            this.Write("        public ");
            
            #line default
            #line hidden
            
            #line 103 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 103 "RepositoryGenerator.tt"
            this.Write(" GetById(");
            
            #line default
            #line hidden
            
            #line 103 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( PrimaryKeyType ));
            
            #line default
            #line hidden
            
            #line 103 "RepositoryGenerator.tt"
            this.Write(" id)\r\n        {\r\n");
            
            #line default
            #line hidden
            
            #line 105 "RepositoryGenerator.tt"
 if (IncludeLogging) { 
            
            #line default
            #line hidden
            
            #line 106 "RepositoryGenerator.tt"
            this.Write("            _logger.LogInformation(\"Retrieving {EntityName} with ID: {Id}\", nameo" +
                    "f(");
            
            #line default
            #line hidden
            
            #line 106 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 106 "RepositoryGenerator.tt"
            this.Write("), id);\r\n");
            
            #line default
            #line hidden
            
            #line 107 "RepositoryGenerator.tt"
 } 
            
            #line default
            #line hidden
            
            #line 108 "RepositoryGenerator.tt"
            this.Write("            return _dataStore.FirstOrDefault(x => x.Id.Equals(id));\r\n        }\r\n\r" +
                    "\n        public IEnumerable<");
            
            #line default
            #line hidden
            
            #line 111 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 111 "RepositoryGenerator.tt"
            this.Write("> GetAll()\r\n        {\r\n");
            
            #line default
            #line hidden
            
            #line 113 "RepositoryGenerator.tt"
 if (IncludeLogging) { 
            
            #line default
            #line hidden
            
            #line 114 "RepositoryGenerator.tt"
            this.Write("            _logger.LogInformation(\"Retrieving all {EntityName} entities\", nameof" +
                    "(");
            
            #line default
            #line hidden
            
            #line 114 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 114 "RepositoryGenerator.tt"
            this.Write("));\r\n");
            
            #line default
            #line hidden
            
            #line 115 "RepositoryGenerator.tt"
 } 
            
            #line default
            #line hidden
            
            #line 116 "RepositoryGenerator.tt"
            this.Write("            return _dataStore.AsEnumerable();\r\n        }\r\n\r\n        public void A" +
                    "dd(");
            
            #line default
            #line hidden
            
            #line 119 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 119 "RepositoryGenerator.tt"
            this.Write(" entity)\r\n        {\r\n");
            
            #line default
            #line hidden
            
            #line 121 "RepositoryGenerator.tt"
 if (IncludeLogging) { 
            
            #line default
            #line hidden
            
            #line 122 "RepositoryGenerator.tt"
            this.Write("            _logger.LogInformation(\"Adding new {EntityName} entity\", nameof(");
            
            #line default
            #line hidden
            
            #line 122 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 122 "RepositoryGenerator.tt"
            this.Write("));\r\n");
            
            #line default
            #line hidden
            
            #line 123 "RepositoryGenerator.tt"
 } 
            
            #line default
            #line hidden
            
            #line 124 "RepositoryGenerator.tt"
            this.Write("            _dataStore.Add(entity);\r\n        }\r\n\r\n        public void Update(");
            
            #line default
            #line hidden
            
            #line 127 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 127 "RepositoryGenerator.tt"
            this.Write(" entity)\r\n        {\r\n");
            
            #line default
            #line hidden
            
            #line 129 "RepositoryGenerator.tt"
 if (IncludeLogging) { 
            
            #line default
            #line hidden
            
            #line 130 "RepositoryGenerator.tt"
            this.Write("            _logger.LogInformation(\"Updating {EntityName} with ID: {Id}\", nameof(" +
                    "");
            
            #line default
            #line hidden
            
            #line 130 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 130 "RepositoryGenerator.tt"
            this.Write("), entity.Id);\r\n");
            
            #line default
            #line hidden
            
            #line 131 "RepositoryGenerator.tt"
 } 
            
            #line default
            #line hidden
            
            #line 132 "RepositoryGenerator.tt"
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 132 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 132 "RepositoryGenerator.tt"
            this.Write(@" existing = _dataStore.FirstOrDefault(x => x.Id.Equals(entity.Id));
            if (existing != null)
            {
                int index = _dataStore.IndexOf(existing);
                _dataStore[index] = entity;
            }
        }

        public void Delete(");
            
            #line default
            #line hidden
            
            #line 140 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( PrimaryKeyType ));
            
            #line default
            #line hidden
            
            #line 140 "RepositoryGenerator.tt"
            this.Write(" id)\r\n        {\r\n");
            
            #line default
            #line hidden
            
            #line 142 "RepositoryGenerator.tt"
 if (IncludeLogging) { 
            
            #line default
            #line hidden
            
            #line 143 "RepositoryGenerator.tt"
            this.Write("            _logger.LogInformation(\"Deleting {EntityName} with ID: {Id}\", nameof(" +
                    "");
            
            #line default
            #line hidden
            
            #line 143 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 143 "RepositoryGenerator.tt"
            this.Write("), id);\r\n");
            
            #line default
            #line hidden
            
            #line 144 "RepositoryGenerator.tt"
 } 
            
            #line default
            #line hidden
            
            #line 145 "RepositoryGenerator.tt"
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 145 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 145 "RepositoryGenerator.tt"
            this.Write(" entity = _dataStore.FirstOrDefault(x => x.Id.Equals(id));\r\n            if (entit" +
                    "y != null)\r\n            {\r\n                _dataStore.Remove(entity);\r\n         " +
                    "   }\r\n        }\r\n");
            
            #line default
            #line hidden
            
            #line 151 "RepositoryGenerator.tt"
 } 
            
            #line default
            #line hidden
            
            #line 152 "RepositoryGenerator.tt"
            this.Write("    }\r\n\r\n    public interface I");
            
            #line default
            #line hidden
            
            #line 154 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 154 "RepositoryGenerator.tt"
            this.Write("Repository\r\n    {\r\n");
            
            #line default
            #line hidden
            
            #line 156 "RepositoryGenerator.tt"
 if (IncludeAsync) { 
            
            #line default
            #line hidden
            
            #line 157 "RepositoryGenerator.tt"
            this.Write("        Task<");
            
            #line default
            #line hidden
            
            #line 157 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 157 "RepositoryGenerator.tt"
            this.Write("> GetByIdAsync(");
            
            #line default
            #line hidden
            
            #line 157 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( PrimaryKeyType ));
            
            #line default
            #line hidden
            
            #line 157 "RepositoryGenerator.tt"
            this.Write(" id);\r\n        Task<IEnumerable<");
            
            #line default
            #line hidden
            
            #line 158 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 158 "RepositoryGenerator.tt"
            this.Write(">> GetAllAsync();\r\n        Task AddAsync(");
            
            #line default
            #line hidden
            
            #line 159 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 159 "RepositoryGenerator.tt"
            this.Write(" entity);\r\n        Task UpdateAsync(");
            
            #line default
            #line hidden
            
            #line 160 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 160 "RepositoryGenerator.tt"
            this.Write(" entity);\r\n        Task DeleteAsync(");
            
            #line default
            #line hidden
            
            #line 161 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( PrimaryKeyType ));
            
            #line default
            #line hidden
            
            #line 161 "RepositoryGenerator.tt"
            this.Write(" id);\r\n");
            
            #line default
            #line hidden
            
            #line 162 "RepositoryGenerator.tt"
 } else { 
            
            #line default
            #line hidden
            
            #line 163 "RepositoryGenerator.tt"
            this.Write("        ");
            
            #line default
            #line hidden
            
            #line 163 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 163 "RepositoryGenerator.tt"
            this.Write(" GetById(");
            
            #line default
            #line hidden
            
            #line 163 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( PrimaryKeyType ));
            
            #line default
            #line hidden
            
            #line 163 "RepositoryGenerator.tt"
            this.Write(" id);\r\n        IEnumerable<");
            
            #line default
            #line hidden
            
            #line 164 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 164 "RepositoryGenerator.tt"
            this.Write("> GetAll();\r\n        void Add(");
            
            #line default
            #line hidden
            
            #line 165 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 165 "RepositoryGenerator.tt"
            this.Write(" entity);\r\n        void Update(");
            
            #line default
            #line hidden
            
            #line 166 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( EntityName ));
            
            #line default
            #line hidden
            
            #line 166 "RepositoryGenerator.tt"
            this.Write(" entity);\r\n        void Delete(");
            
            #line default
            #line hidden
            
            #line 167 "RepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( PrimaryKeyType ));
            
            #line default
            #line hidden
            
            #line 167 "RepositoryGenerator.tt"
            this.Write(" id);\r\n");
            
            #line default
            #line hidden
            
            #line 168 "RepositoryGenerator.tt"
 } 
            
            #line default
            #line hidden
            
            #line 169 "RepositoryGenerator.tt"
            this.Write("    }\r\n}");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
            if ((this.Errors.HasErrors == false)) {
                if (((this.Session != null) 
                            && this.Session.ContainsKey("NamespaceName"))) {
                    object data = this.Session["NamespaceName"];
                    if (typeof(string).IsAssignableFrom(data.GetType())) {
                        this._NamespaceNameField = ((string)(data));
                    }
                    else {
                        this.Error("The type \'System.String\' of the parameter \'NamespaceName\' did not match the type " +
                                "passed to the template");
                    }
                }
                if (((this.Session != null) 
                            && this.Session.ContainsKey("EntityName"))) {
                    object data = this.Session["EntityName"];
                    if (typeof(string).IsAssignableFrom(data.GetType())) {
                        this._EntityNameField = ((string)(data));
                    }
                    else {
                        this.Error("The type \'System.String\' of the parameter \'EntityName\' did not match the type pas" +
                                "sed to the template");
                    }
                }
                if (((this.Session != null) 
                            && this.Session.ContainsKey("PrimaryKeyType"))) {
                    object data = this.Session["PrimaryKeyType"];
                    if (typeof(string).IsAssignableFrom(data.GetType())) {
                        this._PrimaryKeyTypeField = ((string)(data));
                    }
                    else {
                        this.Error("The type \'System.String\' of the parameter \'PrimaryKeyType\' did not match the type" +
                                " passed to the template");
                    }
                }
                if (((this.Session != null) 
                            && this.Session.ContainsKey("IncludeAsync"))) {
                    object data = this.Session["IncludeAsync"];
                    if (typeof(bool).IsAssignableFrom(data.GetType())) {
                        this._IncludeAsyncField = ((bool)(data));
                    }
                    else {
                        this.Error("The type \'System.Boolean\' of the parameter \'IncludeAsync\' did not match the type " +
                                "passed to the template");
                    }
                }
                if (((this.Session != null) 
                            && this.Session.ContainsKey("IncludeLogging"))) {
                    object data = this.Session["IncludeLogging"];
                    if (typeof(bool).IsAssignableFrom(data.GetType())) {
                        this._IncludeLoggingField = ((bool)(data));
                    }
                    else {
                        this.Error("The type \'System.Boolean\' of the parameter \'IncludeLogging\' did not match the typ" +
                                "e passed to the template");
                    }
                }
                if (((this.Session != null) 
                            && this.Session.ContainsKey("ModelUsing"))) {
                    object data = this.Session["ModelUsing"];
                    if (typeof(string).IsAssignableFrom(data.GetType())) {
                        this._ModelUsingField = ((string)(data));
                    }
                    else {
                        this.Error("The type \'System.String\' of the parameter \'ModelUsing\' did not match the type pas" +
                                "sed to the template");
                    }
                }
            }

        }
    }
    
    public class RepositoryGeneratorBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
