<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>1.0.0</Version>
		<Product>Samayas Main Library</Product>
		<Description>Samayas Main Library Description.</Description>
		<Copyright>Samayas Consulting</Copyright>
		<Authors>Samayas Consulting</Authors>
	</PropertyGroup>

	<PropertyGroup>
		<IsPackable>true</IsPackable>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageId>MainLibrary</PackageId>
		<PackageVersion>1.0.0</PackageVersion>
		<PackageIconUrl>https://www.samayas.eu/images/logo/nugetpackage.png</PackageIconUrl>
		<PackageTags>netcore;samayas;sample</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components" Version="9.0.6" />
		<PackageReference Include="NETStandard.Library" Version="2.0.3" />
	</ItemGroup>

</Project>
