<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
		<PackageReference Include="MSTest" Version="4.3.2" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
	</ItemGroup>

	<ItemGroup>
		<Analyzer Include="D:\Projects\Github\VideoSamples\Roslyn\CodeAnalyzers\Analyzer\bin\Debug\netstandard2.0\Samayas.Tools.CodeAnalyzers.Analyzers.dll" />
		<Analyzer Include="D:\Projects\Github\VideoSamples\Roslyn\CodeAnalyzers\CodeFixes\bin\Debug\netstandard2.0\Samayas.Tools.CodeAnalyzers.CodeFixes.dll" />
	</ItemGroup>

</Project>
