<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>2.0.0</Version>
		<Product>Samayas Secondary Library</Product>
		<Description>Samayas Secondary Library Description.</Description>
		<Copyright>Samayas Consulting</Copyright>
		<Authors>Samayas Consulting</Authors>
	</PropertyGroup>
	
	<PropertyGroup>
		<NuspecUpdaterTasksAssemblyPath>$(MSBuildThisFileDirectory)..\MSBuildTasks\bin\Debug\netstandard2.0\MSBuildTasks.dll</NuspecUpdaterTasksAssemblyPath>
	</PropertyGroup>

	<UsingTask TaskName="MSBuildTasks.NuspecUpdaterTask" AssemblyFile="$(NuspecUpdaterTasksAssemblyPath)" />

	<Target Name="RunMyPostProcessTask" AfterTargets="Build" Condition="'$(Configuration)' != 'Release'">
		<Message Text="----- Executing Custom Post-Processing -----" Importance="high" />
		<NuspecUpdaterTask
			NuspecFilePath="$(MSBuildThisFileDirectory)..\Nuget\Library.nuspec"
			ProjectFiles="$(MSBuildThisFileDirectory)MainLibrary.csproj;$(MSBuildThisFileDirectory)..\SecondaryLibrary\SecondaryLibrary.csproj" />
	</Target>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components" Version="9.0.7" />
		<PackageReference Include="NETStandard.Library" Version="2.0.3" />
	</ItemGroup>

</Project>
