//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samayas.Tools.CodeAnalyzers.CodeFixes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeFixResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeFixResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Samayas.Tools.CodeAnalyzers.CodeFixes.CodeFixResources", typeof(CodeFixResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RenameToEntity.
        /// </summary>
        internal static string DataClassSuffixEntityForBaseEntityClassFixProviderKey {
            get {
                return ResourceManager.GetString("DataClassSuffixEntityForBaseEntityClassFixProviderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename to end with &apos;Entity&apos;.
        /// </summary>
        internal static string DataClassSuffixEntityForBaseEntityClassFixProviderTitle {
            get {
                return ResourceManager.GetString("DataClassSuffixEntityForBaseEntityClassFixProviderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertParameterlessConstructor.
        /// </summary>
        internal static string DataMethodEmptyConstructorForBaseEntityBaseClassFixProviderKey {
            get {
                return ResourceManager.GetString("DataMethodEmptyConstructorForBaseEntityBaseClassFixProviderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a parameterless Constructor.
        /// </summary>
        internal static string DataMethodEmptyConstructorForBaseEntityBaseClassFixProviderTitle {
            get {
                return ResourceManager.GetString("DataMethodEmptyConstructorForBaseEntityBaseClassFixProviderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddExcludeFromCodeCoverageClassAttribute.
        /// </summary>
        internal static string TestClassAttributeExcludeFromCodeCoverageForBaseTestClassFixProviderKey {
            get {
                return ResourceManager.GetString("TestClassAttributeExcludeFromCodeCoverageForBaseTestClassFixProviderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add [ExcludeFromCodeCoverage()] attribute to TestClass.
        /// </summary>
        internal static string TestClassAttributeExcludeFromCodeCoverageForBaseTestClassFixProviderTitle {
            get {
                return ResourceManager.GetString("TestClassAttributeExcludeFromCodeCoverageForBaseTestClassFixProviderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RenameToViewModel.
        /// </summary>
        internal static string WebClassSuffixViewModelForBaseTestClassFixProviderKey {
            get {
                return ResourceManager.GetString("WebClassSuffixViewModelForBaseTestClassFixProviderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename to end with &apos;ViewModel&apos;.
        /// </summary>
        internal static string WebClassSuffixViewModelForBaseTestClassFixProviderTitle {
            get {
                return ResourceManager.GetString("WebClassSuffixViewModelForBaseTestClassFixProviderTitle", resourceCulture);
            }
        }
    }
}
